### ISSUE TITLE
oncreate.ecl not working properly

### ISSUE THREAD

**Issue by StrobelArtesao** [polserver/ModernDistro#67]
When creating a new Character and choosing Paladin, warior, ninja or samurai The oncreate.ecl can't create the newbie items as practice krysis, longsword and shield (not sure if other items are created.

When creating a new Character and choosing Mage or Necromancer, the client is disconected and in pol cmd it shows "Starting skill values incorrect"

**Comment by Admin-Yukiko** [comment]
I am constantly having to recreate my characters on my development server due to the need to wipe world data and I always choose the mage profession. I do not have this issue. However, I am running the latest, or close to the latest, client. I haven't tested the necromancer option. We will see if that works for me.

What client version are you using?

**Comment by Admin-Yukiko** [comment]
I have tested this on the official client and it works creating a mage and necromancer. I also tested this with ClassicUO and the client froze on the "Creating character" screen. I have never been able to create a mage on ClassicUO. Since Strobel posted this issue he informed me he was using ClassicUO to log in and create his character. My recommendation is contact the ClassicUO team and report the issue.
