### ISSUE TITLE
Cooking not working

### ISSUE THREAD

**Issue by StrobelArtesao** [polserver/ModernDistro#78]
You can't dobbleclick any raw food to cook it. And you cant make fire to cook it too

**Comment by Admin-Yukiko** [comment]
Cooking works differently on the Modern Distro than most free shards because it is modeled after the official servers. To cook food you need one of the following items, small pan, medium pan, frypan, large pan, large wooden bowl, spit, wooden bowl or rolling pin. Any of these items, when used (double-clicked) will open the cooking gump.

Foods that require the oven to prepare should now work.
Foods that require fire to cook can now be prepared when you are near a campfire, campfire embers, brazier, fire pit, bonfire, fireplace, and a wooden stove. The sources of fire that can be lit by using them, must be lit in order to cook near them.

Cooking has been updated with my last commits.
