### ISSUE TITLE
pkg/skills\tinkering/tinkerTraps.src does not exist!

### ISSUE THREAD

**Issue by andrtechno** [polserver/ModernDistro#88]

**Comment by Admin-Yukiko** [comment]
pkg/skills\tinkering/tinkerTraps.src should no longer be needed because the trap system is now handled in /pkg/items/traps. The only script that was attempting to use tinkerTraps was the shovels use script. I thought I had found all the scripts that used the old trap method but I missed that one. I commented out what I think is the relevant code. Please test it and report back here if you find any issues.
